version: '3'

services:
  sf5-api-server:
    build: ./docker/php
    image: sf5-api
    depends_on:
      - database
    volumes:
      - ./:/application:cached
      - /application/var/sessions/
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: db_sf5_social_network_api
    ports:
      - 5432:5432
  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application:cached
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - sf5-api-server